FROM node:15.7-alpine as build_node
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build --prod

FROM nginx:1.19.6-alpine AS prod-stage
COPY --from=build_node /app/dist/PokedexApp /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]